### ISSUE TITLE
Malformed replacements in conda_build_config.yaml

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/qt-main-feedstock#79]
https://github.com/conda-forge/qt-main-feedstock/blob/331aac5f4b7b9fad0dd59b8f60ed70da01944e6a/recipe/conda_build_config.yaml#L16
```
replacements:
  all_replacements:
    - tag: 'qmake build metadata'
      glob_patterns:
        - '*.pri'
        - '*.prl'
      regex_re: '(?:-L|-I)?\"?([^;\s]+\/sysroot)'
      replacement_re: '$(CONDA_BUILD_SYSROOT)'
      regex_rg: '([^;\s"]+/sysroot)'
```

seem to be malformed. in qt-webengine, I used `sed` to replace them with the actual value of `${CONDA_BUILD_SYSROOT}`, fully expanded.

I'm not sure if there is a right syntax to use here, or if we should it manaually do the replacement in the build script if we can't do it in the config file.
